language: python
sudo: false
python:
  - "3.7-dev"

install:
  - pip install -r requirements-dev.txt
  # - pip install -e .

script:
  - make prcheck

after_success:
  - codecov --token ${!codecov-token}
